version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeper
    container_name: zookeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  broker:
    image: confluentinc/cp-enterprise-kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,LOCAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,LOCAL:PLAINTEXT
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      
  config:
    image: jipram017/event-tracing-config:1.0.0
    container_name: config
    depends_on:
      - zookeeper
      - broker
    environment:
      - spring.kafka.bootstrap-servers=broker:29092

  connect:
    image: confluentinc/cp-kafka-connect:5.4.0-beta1
    hostname: connect
    container_name: connect
    depends_on:
      - zookeeper
      - broker
      - config
    volumes:
      - ./connect:/usr/share/data
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: /usr/share/java,/usr/share/confluent-hub-components
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR
      
  rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    depends_on:
      - zookeeper
      - broker
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - ElasticData:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
      
  app4:
    image: jipram017/event-tracing-app4:1.0.0
    container_name: app4
    environment:
      - jaeger.tracer.host=jaeger
      - jaeger.tracer.port=6831
    ports:
      - "8096:8096"
    restart: always
    
  app3:
    image: jipram017/event-tracing-app3:1.0.0
    container_name: app3
    depends_on:
      - zookeeper
      - broker
      - config
      - connect
    environment:
      - spring.kafka.bootstrap-servers=broker:29092
      - jaeger.tracer.host=jaeger
      - jaeger.tracer.port=6831
    restart: always
    
  app2:
    image: jipram017/event-tracing-app2:1.0.0
    container_name: app2
    depends_on:
      - zookeeper
      - broker
      - config
      - connect
    environment:
      - spring.kafka.bootstrap-servers=broker:29092
      - app2.rest.app-url=http://app4:8096
      - jaeger.tracer.host=jaeger
      - jaeger.tracer.port=6831
    restart: always
    
  app1:
    image: jipram017/event-tracing-app1:1.0.0
    container_name: app1
    depends_on:
      - zookeeper
      - broker
      - config
      - connect
    environment:
      - spring.kafka.bootstrap-servers=broker:29092
      - jaeger.tracer.host=jaeger
      - jaeger.tracer.port=6831
    restart: always
    
  collect:
    image: jipram017/event-tracing-collect:1.0.0
    container_name: collect
    depends_on:
      - zookeeper
      - broker
      - config
      - connect
    environment:
      - spring.kafka.bootstrap-servers=broker:29092
      - collect.jaeger.host=http://jaeger
      - collect.jaeger.port=14268
    restart: always
    
volumes:
  ElasticData:
  ConnectData:

